// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUg5RVAbriUWBNlx0mc4EwLYT0yQTMaw',
    appId: '1:313526013474:web:1f72e303dc478905b4c47b',
    messagingSenderId: '313526013474',
    projectId: 'level-up-cb693',
    authDomain: 'level-up-cb693.firebaseapp.com',
    storageBucket: 'level-up-cb693.firebasestorage.app',
    measurementId: 'G-DXPPEPL2PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9sq32j2MjtXmf1HtRv53EOm_v5ybK7hM',
    appId: '1:313526013474:android:bc99ea72062c291eb4c47b',
    messagingSenderId: '313526013474',
    projectId: 'level-up-cb693',
    storageBucket: 'level-up-cb693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFu_RxZhzSHnfWd6CLQ31dw7bPgqngMbc',
    appId: '1:313526013474:ios:fabe439d94d17bb2b4c47b',
    messagingSenderId: '313526013474',
    projectId: 'level-up-cb693',
    storageBucket: 'level-up-cb693.firebasestorage.app',
    iosBundleId: 'com.teknogenetik.levelup.levelUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFu_RxZhzSHnfWd6CLQ31dw7bPgqngMbc',
    appId: '1:313526013474:ios:fabe439d94d17bb2b4c47b',
    messagingSenderId: '313526013474',
    projectId: 'level-up-cb693',
    storageBucket: 'level-up-cb693.firebasestorage.app',
    iosBundleId: 'com.teknogenetik.levelup.levelUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvUg5RVAbriUWBNlx0mc4EwLYT0yQTMaw',
    appId: '1:313526013474:web:c72a123fd3b3fb7fb4c47b',
    messagingSenderId: '313526013474',
    projectId: 'level-up-cb693',
    authDomain: 'level-up-cb693.firebaseapp.com',
    storageBucket: 'level-up-cb693.firebasestorage.app',
    measurementId: 'G-CJTBW14CD0',
  );
}
